# Generated by Django 4.0.6 on 2023-03-04 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('hobby', models.CharField(choices=[('SPORTS', 'SPORTS'), ('FITNESS', 'FITNESS'), ('MUSIC', 'MUSIC'), ('TRAVEL', 'TRAVEL'), ('READING', 'READING'), ('COOKING', 'COOKING'), ('ART & CULTURE', 'ART & CULTURE'), ('GAMING', 'GAMING'), ('FOOD & DRINK', 'FOOD & DRINK'), ('VOLUNTEER WORK', 'VOLUNTEER WORK')], max_length=50)),
                ('favshows', models.CharField(choices=[('COMEDY', 'COMEDY'), ('DRAMA', 'DRAMA'), ('SCIENCE-FICTION', 'SCIENCE-FICTION'), ('FANTASY', 'FANTASY'), ('CRIME', 'CRIME')], max_length=50)),
                ('gpref', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=50)),
                ('agepref', models.CharField(choices=[('18-22', '18-22'), ('23-27', '23-27'), ('28-32', '28-32'), ('33-40', '33-40'), ('41+', '41')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
