# Generated by Django 4.0.6 on 2023-03-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushmetapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='agepref',
            field=models.CharField(choices=[('18-22', '18-22'), ('23-27', '23-27'), ('28-32', '28-32'), ('33-40', '33-40'), ('41+', '41+')], max_length=50),
        ),
    ]
