# Generated by Django 4.0.6 on 2023-03-05 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushmetapp', '0002_profile_name_alter_profile_agepref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50)),
                ('gpref', models.CharField(max_length=50)),
            ],
        ),
    ]
