# Generated by Django 4.0.6 on 2023-03-05 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushmetapp', '0004_demoprofile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoprofile',
            name='about',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='demoprofile',
            name='interest',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demoprofile',
            name='pickup',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='demoprofile',
            name='show',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
