# Generated by Django 4.0.6 on 2023-03-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crushmetapp', '0005_demoprofile_about_demoprofile_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demoprofile',
            name='city',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='demoprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demoprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
