# Generated by Django 4.0.6 on 2023-03-05 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crushmetapp', '0006_demoprofile_city_demoprofile_dob_demoprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demoprofile',
            old_name='image',
            new_name='img',
        ),
    ]
